# @package _global_

defaults:
  # override config either in this file or using experiment config
  - _self_
  - experiment: null # experiment configs allow for version control of specific hyperparameters

data_path: /fast/grantn2/BBBPermeability/Chemformer/molbart/data/zinc/x000.csv #null
smiles_column: SMILES #canonical_smiles
mol_opt_tokens_path: mol_opt_tokens.txt
prop_pred_tokens_path: prop_pred_tokens.txt
num_unused_tokens: 180
tokeniser_path: new_vocab_zinc.json
